# Generated by Django 4.1.5 on 2023-01-30 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('Project_name', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('repo_link', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=64)),
                ('second_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('Act.', 'Active'), ('Clos.', 'Closed')], default='Act.', max_length=50)),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToDoApp.project')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToDoApp.users')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='permitted_users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToDoApp.users'),
        ),
    ]
